[tool.bandit]
exclude_dirs = ["example/blog/env", ]
skips = ["B101", "B105", "B308", "B703"]

[tool.black]
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.pytest_cache
    | \.tox
    | \.venv
    | venv
    | env
    | _build
    | buck-out
    | build
    | dist
    | django_ckeditor_5
    | migrations
  )/
)
'''

[tool.flake8]
count = true
exclude = '.git,__pycache__,docs/source/conf.py,old,build,dist,env'
ignore = ['B009', 'E302', 'F401', 'W292', 'W391']
max-complexity = 10
max-line-length = 140
per-file-ignores = [
    '__init__.py:F401',
]
show-source = true
statistics = true

[tool.isort]
profile = "black"
skip = ["env", "migrations", "build"]

[tool.mypy]
exclude = [
    'example/blog/articles/migrations',
    "build",
    "env",
    "example/blog/django_ckeditor_5"
]
ignore_missing_imports = true
install_types = true
