[project]
name = 'django-ckeditor-5'
version = '0.1.8'
dependencies = [
  'Django == 4.1',
  'Pillow == 9.0.1',
]

[project.optional-dependencies]
dev = [
  'bandit == 1.7.4',
  'black == 22.8.0',
  'codespell == 2.2.1',
  'coverage == 6.3.3',
  'flake8 == 5.0.4',
  'flake8-2020 == 1.7.0',
  'flake8-bugbear == 22.8.22',
  'flake8-comprehensions == 3.10.0',
  'Flake8-pyproject == 1.1.0.post0',
  'isort == 5.10.1',
  'mypy == 0.971',
  'mypy-extensions == 0.4.3',
  'pylint == 2.15.0',
  'pytest == 7.1.2',
  'pytest-cov == 3.0.0',
  'pytest-django == 4.5.2',
  'pytest-mock == 3.7.0',
  'pyupgrade == 2.37.3',
  'safety == 2.1.1',
  'types-setuptools == 65.3.0',
  'typing_extensions == 4.1.1',
]

[tool.bandit]
exclude_dirs = ["example/blog/env", ]
skips = ["B101", "B105", "B308", "B703"]

[tool.black]
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.pytest_cache
    | \.tox
    | \.venv
    | venv
    | env
    | _build
    | buck-out
    | build
    | dist
    | django_ckeditor_5
    | migrations
  )/
)
'''

[tool.flake8]
count = true
exclude = '.git,__pycache__,docs/source/conf.py,old,build,dist,env'
ignore = ['B009', 'E302', 'F401', 'W292', 'W391']
max-complexity = 10
max-line-length = 140
per-file-ignores = [
    '__init__.py:F401',
]
show-source = true
statistics = true

[tool.isort]
profile = "black"
skip = ["env", "migrations", "build"]

[tool.mypy]
exclude = [
    'example/blog/articles/migrations',
    "build",
    "env",
    "example/blog/django_ckeditor_5"
]
ignore_missing_imports = true
install_types = true
