[tool.bandit]
exclude_dirs = ["example/blog/env", ]
skips = ["B101", "B105", "B308", "B703"]

[tool.black]
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.pytest_cache
    | \.tox
    | \.venv
    | venv
    | env
    | _build
    | buck-out
    | build
    | dist
    | django_ckeditor_5
    | migrations
  )/
)
'''